"""
MockGovPortal — the default adapter.

Answers from `data/mock_portal.json` (generated by `data/generate.py`),
simulates realistic latency and injects the demo dataset's flaws
(return-not-filed, cancelled GSTIN, debarment hits, etc.).
"""
from __future__ import annotations

import datetime as dt
import json
import random
import time
from pathlib import Path

from app.core.config import settings
from app.integration.adapter import GovPortalAdapter, PortalResponse, register_adapter
from app.core.logging import get_logger

logger = get_logger(__name__)


def _now() -> str:
    return dt.datetime.now(dt.timezone.utc).isoformat()


@register_adapter
class MockGovPortal(GovPortalAdapter):
    name = "mock"

    def __init__(self, data_file: str | None = None):
        path = Path(data_file or settings.mock_portal_data)
        self._data: dict = {}
        if path.exists():
            try:
                self._data = json.loads(path.read_text(encoding="utf-8"))
            except Exception as exc:  # pragma: no cover
                logger.error("mock portal data unreadable: %s", exc)
        else:
            logger.warning("mock portal data not found at %s — empty registry", path)

    # -- helpers ---------------------------------------------------------
    def _respond(
        self, kind: str, key: str, *, latency_range=(40, 260), inject_miss: float = 0.0
    ) -> PortalResponse:
        start = time.perf_counter()
        time.sleep(random.uniform(*latency_range) / 1000.0)
        lookup = self._data.get(kind, {})
        entry = lookup.get(key)
        if entry is None or random.random() < inject_miss:
            return PortalResponse(
                found=False,
                data={},
                source=self.name,
                retrieved_at=_now(),
                latency_ms=int((time.perf_counter() - start) * 1000),
                error="record not found in registry",
            )
        return PortalResponse(
            found=True,
            data=entry,
            source=self.name,
            retrieved_at=_now(),
            latency_ms=int((time.perf_counter() - start) * 1000),
        )

    # -- statutory lookups ----------------------------------------------
    def verify_udyam(self, udyam_no: str) -> PortalResponse:
        return self._respond("udyam", udyam_no.strip().upper())

    def verify_gstin(self, gstin: str) -> PortalResponse:
        return self._respond("gstin", gstin.strip().upper())

    def gst_return_status(self, gstin: str) -> PortalResponse:
        # returns the return-filing status from the seeded dataset
        resp = self._respond("gstin", gstin.strip().upper())
        if not resp.found:
            return resp
        filings = resp.data.get("returns", {})
        latest = filings.get("latest", {})
        return PortalResponse(
            found=True,
            data={
                "gstin": gstin.strip().upper(),
                "status": resp.data.get("status"),
                "return_status": latest.get("status", "unknown"),
                "period": latest.get("period"),
                "filed_on": latest.get("filed_on"),
            },
            source=self.name,
            retrieved_at=_now(),
            latency_ms=resp.latency_ms,
        )

    def verify_pan(self, pan: str) -> PortalResponse:
        return self._respond("pan", pan.strip().upper())

    def mca_company(self, cin: str) -> PortalResponse:
        return self._respond("mca", cin.strip().upper())

    def epfo_status(self, epfo_no: str) -> PortalResponse:
        return self._respond("epfo", epfo_no.strip())

    def esic_status(self, esic_no: str) -> PortalResponse:
        return self._respond("esic", esic_no.strip())

    def startup_status(self, dpiit_no: str) -> PortalResponse:
        return self._respond("startup", dpiit_no.strip().upper())

    def nsic_status(self, nsic_no: str) -> PortalResponse:
        return self._respond("nsic", nsic_no.strip().upper())

    def check_blacklist(
        self, name: str, pan: str | None = None, cin: str | None = None
    ) -> PortalResponse:
        entries = self._data.get("blacklist", [])
        hits = []
        for e in entries:
            matched = False
            if pan and e.get("pan") and pan.upper() == e["pan"].upper():
                matched = True
            if cin and e.get("cin") and cin.upper() == e["cin"].upper():
                matched = True
            if not matched and e.get("name") and name:
                # name match (case-insensitive) — the check module also does fuzzy
                if e["name"].strip().lower() in name.strip().lower():
                    matched = True
            if matched:
                hits.append(e)
        return PortalResponse(
            found=bool(hits),
            data={"matches": hits},
            source=self.name,
            retrieved_at=_now(),
            latency_ms=int(random.uniform(40, 180)),
        )

    def digilocker_verify(self, issued_uri: str) -> PortalResponse:
        return self._respond("digilocker", issued_uri)