"""initial schema

Revision ID: 1f8c6d979932
Revises: 
Create Date: 2026-08-26 15:47:25.219442
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1f8c6d979932'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###