"""bidder bank/phone columns

Revision ID: 429533a83b0b
Revises: 1f8c6d979932
Create Date: 2026-08-26 18:43:21.227052
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '429533a83b0b'
down_revision: Union[str, None] = '1f8c6d979932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bidders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_account', app.db.types.EncryptedString(length=64), nullable=True))
        batch_op.add_column(sa.Column('phone', app.db.types.EncryptedString(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bidders', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('bank_account')

    # ### end Alembic commands ###